version: '3.9'

services:
  interview-service:
    build:
      context: .
    container_name: interview-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      ## DATABASE CONFIGURATION
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/aierview
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_DEVTOOLS_RESTART_ENABLED=FALSE
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=FALSE
    command: mvn spring-boot:run
    networks:
      - aierview-network

networks:
  aierview-network:
    external: true
