# SPRING JPA CONFIGURATION
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://192.168.49.2:30787/aierview
spring.datasource.username=postgres
spring.datasource.password=postgres
# DEV TOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
